import type { Report } from './types';

export const REPORTS: Report[] = [
  {
    _id: '1',
    description: 'A large pothole has formed on the main road, causing traffic issues.',
    latitude: 34.0522,
    longitude: -118.2437,
    urgency: 'Moderate',
    status: 'New',
    imageUrl: 'https://placehold.co/600x400.png',
    reportedBy: 'user1',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '2',
    description: 'Fallen tree blocking the sidewalk on Elm Street.',
    latitude: 34.055,
    longitude: -118.25,
    urgency: 'High',
    status: 'In Progress',
    imageUrl: 'https://placehold.co/600x400.png',
    reportedBy: 'user2',
    assignedTo: 'volunteer1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    _id: '3',
    description: 'Broken streetlight at the park entrance, it is very dark at night.',
    latitude: 34.048,
    longitude: -118.24,
    urgency: 'Low',
    status: 'Resolved',
    imageUrl: 'https://placehold.co/600x400.png',
    reportedBy: 'user3',
    assignedTo: 'volunteer2',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '4',
    description: 'Flooding near the river crossing after heavy rain.',
    latitude: 40.7128,
    longitude: -74.006,
    urgency: 'High',
    status: 'New',
    imageUrl: 'https://placehold.co/600x400.png',
    reportedBy: 'user4',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    _id: '5',
    description: 'Waste bins overflowing at the bus stop on 5th Avenue.',
    latitude: 40.715,
    longitude: -74.002,
    urgency: 'Low',
    status: 'In Progress',
    reportedBy: 'user5',
    assignedTo: 'volunteer3',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: '6',
    description: 'Power line down after the storm last night.',
    latitude: 40.718,
    longitude: -74.008,
    urgency: 'High',
    status: 'Resolved',
    imageUrl: 'https://placehold.co/600x400.png',
    reportedBy: 'user1',
    assignedTo: 'volunteer1',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
];
